version: 2.1

base_img: &base_img
  docker:
    - image: cimg/node:13.8.0

jobs:
  build:
    <<: *base_img
    steps:
      - checkout
      - run:
          command: npm i
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/.node_modules

  test:
    <<: *base_img
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
      - run: npm test

  analyze:
    <<: *base_img
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
      - run: npm audit


workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - anaylyze:
          requires:
            - test
